name: first workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Hellow World
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "GoodBye"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
